services:
  prometheus:
    ports: !override
      - "127.0.0.1:19090:9090"

  keycloak:
    command:
      - start
      - --import-realm
    environment:
      KC_HOSTNAME: "193.123.81.23"
      KC_HOSTNAME_PORT: "8093"
      KC_HOSTNAME_STRICT: "true"
      KC_HOSTNAME_STRICT_HTTPS: "true"

  api-gateway:
    ports: !override []

  edge:
    ports: !override
      - "0.0.0.0:8093:443"

  contractor-frontend:
    ports: !override
      - "0.0.0.0:8082:80"

  mobile-pwa:
    ports: !override
      - "0.0.0.0:8081:80"
