-- ============================================================
-- 002_rca_demo_alarms.sql
-- Demo alarm data for RCA dashboard testing
--
-- Patterns embedded:
--   • 4 source systems: Zabbix, Alertmanager, Grafana, Dynatrace
--   • All severities: critical, high, medium, low
--   • 3 categories: network, compute, application
--   • Anomaly spike: ~20 alarms in a single 2 AM window (5 days ago)
--   • Co-occurrence: Zabbix + Alertmanager fire together repeatedly
--   • SLA breaches: several critical/high alarms marked BREACHED
--   • Spread over 30 days with realistic hourly variation
-- ============================================================

-- Helper: insert with a unique dedup_hash (md5 of alarm_id)
-- We use NOW() offsets so data is always "recent" relative to run time.

INSERT INTO unified_alarms
  (source_system, alarm_id, severity, priority, title, description,
   site_id, host_name, service_name, category,
   first_occurrence, last_occurrence, status, probable_cause, event_count,
   dedup_hash, region, cluster, vendor, technology_domain,
   assignment_group, oncall_group, sla_class, sla_status, created_at)
VALUES

-- ── Zabbix – Network – Critical (off-hours anomaly spike, 5 days ago 02:xx) ──
('Zabbix','ZBX-001','critical','P1','Core Router BGP Session Down',
 'BGP session to upstream provider dropped. AS 65001 unreachable.',
 'SITE-DC1','core-router-01','BGP','network',
 NOW()-INTERVAL '5 days 2 hours 10 minutes', NOW()-INTERVAL '5 days 2 hours 10 minutes',
 'FIRING','BGP keepalive timeout – link flap detected',3,
 md5('ZBX-001-dc1'),'EMEA','Cluster-A','Cisco','IP/MPLS',
 'Network Ops','NOC-OnCall','Gold','BREACHED', NOW()-INTERVAL '5 days 2 hours 10 minutes'),

('Zabbix','ZBX-002','critical','P1','Core Switch Stack Failover',
 'Primary stack member failed. Redundancy degraded.',
 'SITE-DC1','core-sw-01','STP','network',
 NOW()-INTERVAL '5 days 2 hours 5 minutes', NOW()-INTERVAL '5 days 2 hours 5 minutes',
 'FIRING','Hardware fault – stack cable disconnected',1,
 md5('ZBX-002-dc1'),'EMEA','Cluster-A','Cisco','IP/MPLS',
 'Network Ops','NOC-OnCall','Gold','BREACHED', NOW()-INTERVAL '5 days 2 hours 5 minutes'),

('Zabbix','ZBX-003','critical','P1','Firewall CPU 100%',
 'Firewall CPU sustained at 100% for 10+ minutes. New sessions dropping.',
 'SITE-DC1','fw-01','Security','network',
 NOW()-INTERVAL '5 days 2 hours', NOW()-INTERVAL '5 days 2 hours',
 'FIRING','DDoS traffic pattern detected – SYN flood',7,
 md5('ZBX-003-dc1'),'EMEA','Cluster-A','Fortinet','Security',
 'Security Ops','SOC-OnCall','Platinum','BREACHED', NOW()-INTERVAL '5 days 2 hours'),

('Zabbix','ZBX-004','high','P2','Distribution Switch Port Errors',
 'High error rate on uplink ports – packet loss >5%.',
 'SITE-DC1','dist-sw-02','Ethernet','network',
 NOW()-INTERVAL '5 days 2 hours 15 minutes', NOW()-INTERVAL '5 days 2 hours 15 minutes',
 'FIRING','Duplex mismatch on uplink',2,
 md5('ZBX-004-dc1'),'EMEA','Cluster-A','Cisco','IP/MPLS',
 'Network Ops','NOC-OnCall','Gold','AT_RISK', NOW()-INTERVAL '5 days 2 hours 15 minutes'),

('Zabbix','ZBX-005','high','P2','WAN Link Utilisation >90%',
 'Primary WAN link sustained above 90% utilisation.',
 'SITE-DC1','wan-router-01','WAN','network',
 NOW()-INTERVAL '5 days 2 hours 20 minutes', NOW()-INTERVAL '5 days 2 hours 20 minutes',
 'FIRING','Traffic surge following BGP failover',4,
 md5('ZBX-005-dc1'),'EMEA','Cluster-A','Juniper','IP/MPLS',
 'Network Ops','NOC-OnCall','Silver','AT_RISK', NOW()-INTERVAL '5 days 2 hours 20 minutes'),

-- Alertmanager fires in same 2am window (co-occurrence with Zabbix)
('Alertmanager','AM-001','critical','P1','Kubernetes Node NotReady',
 'Node k8s-node-03 has been NotReady for >5 minutes.',
 'SITE-DC1','k8s-node-03','Kubernetes','compute',
 NOW()-INTERVAL '5 days 2 hours 8 minutes', NOW()-INTERVAL '5 days 2 hours 8 minutes',
 'FIRING','OOM kill cascaded from memory pressure during traffic spike',2,
 md5('AM-001-dc1'),'EMEA','Cluster-A','AWS','Cloud/Kubernetes',
 'Platform Ops','K8S-OnCall','Gold','BREACHED', NOW()-INTERVAL '5 days 2 hours 8 minutes'),

('Alertmanager','AM-002','critical','P1','etcd Leader Election',
 'etcd lost quorum – leader election triggered.',
 'SITE-DC1','k8s-etcd-01','etcd','compute',
 NOW()-INTERVAL '5 days 2 hours 3 minutes', NOW()-INTERVAL '5 days 2 hours 3 minutes',
 'FIRING','Network partition caused by router failure',1,
 md5('AM-002-dc1'),'EMEA','Cluster-A','AWS','Cloud/Kubernetes',
 'Platform Ops','K8S-OnCall','Platinum','BREACHED', NOW()-INTERVAL '5 days 2 hours 3 minutes'),

('Alertmanager','AM-003','high','P2','PodCrashLoopBackOff – api-service',
 'api-service pod restarting >5 times in 10 minutes.',
 'SITE-DC1','k8s-node-01','api-service','application',
 NOW()-INTERVAL '5 days 2 hours 12 minutes', NOW()-INTERVAL '5 days 2 hours 12 minutes',
 'FIRING','Dependency on database unavailable',5,
 md5('AM-003-dc1'),'EMEA','Cluster-A','AWS','Cloud/Kubernetes',
 'App Ops','APP-OnCall','Gold','BREACHED', NOW()-INTERVAL '5 days 2 hours 12 minutes'),

('Alertmanager','AM-004','high','P2','PostgreSQL Replication Lag >30s',
 'Standby replica 30+ seconds behind primary.',
 'SITE-DC1','db-replica-01','PostgreSQL','compute',
 NOW()-INTERVAL '5 days 2 hours 18 minutes', NOW()-INTERVAL '5 days 2 hours 18 minutes',
 'FIRING','Disk I/O saturation on replica node',3,
 md5('AM-004-dc1'),'EMEA','Cluster-A','Dell','Database',
 'DBA','DBA-OnCall','Gold','AT_RISK', NOW()-INTERVAL '5 days 2 hours 18 minutes'),

-- Grafana also fires in the same 2am window
('Grafana','GF-001','high','P2','API Response Time >5s',
 'p99 latency on /api/orders exceeded 5 seconds.',
 'SITE-DC1','app-server-02','order-service','application',
 NOW()-INTERVAL '5 days 2 hours 6 minutes', NOW()-INTERVAL '5 days 2 hours 6 minutes',
 'FIRING','Upstream DB connection pool exhausted',8,
 md5('GF-001-dc1'),'EMEA','Cluster-A','AWS','Application',
 'App Ops','APP-OnCall','Silver','BREACHED', NOW()-INTERVAL '5 days 2 hours 6 minutes'),

('Grafana','GF-002','medium','P3','Error Rate >1% – payment-service',
 'HTTP 5xx error rate on payment-service elevated.',
 'SITE-DC1','app-server-03','payment-service','application',
 NOW()-INTERVAL '5 days 2 hours 22 minutes', NOW()-INTERVAL '5 days 2 hours 22 minutes',
 'FIRING','Downstream timeout to payment gateway',12,
 md5('GF-002-dc1'),'EMEA','Cluster-A','AWS','Application',
 'App Ops','APP-OnCall','Silver','AT_RISK', NOW()-INTERVAL '5 days 2 hours 22 minutes'),

-- ── Regular daily Zabbix alarms spread across 30 days ──────────────────────
('Zabbix','ZBX-010','medium','P3','CPU Usage >80% – web-01',
 'Web server CPU sustained above 80% during business hours.',
 'SITE-DC2','web-01','Apache','compute',
 NOW()-INTERVAL '28 days 10 hours', NOW()-INTERVAL '28 days 10 hours',
 'RESOLVED','High traffic load – autoscaled','2',
 md5('ZBX-010-dc2'),'APAC','Cluster-B','HP','x86 Compute',
 'Platform Ops','SYS-OnCall','Bronze','ON_TRACK', NOW()-INTERVAL '28 days 10 hours'),

('Zabbix','ZBX-011','high','P2','Disk Usage >90% – db-01',
 '/data partition at 93% – database write risk.',
 'SITE-DC2','db-01','MySQL','compute',
 NOW()-INTERVAL '26 days 14 hours', NOW()-INTERVAL '26 days 14 hours',
 'RESOLVED','Log rotation failed – resolved by cleanup',1,
 md5('ZBX-011-dc2'),'APAC','Cluster-B','Dell','Database',
 'DBA','DBA-OnCall','Gold','ON_TRACK', NOW()-INTERVAL '26 days 14 hours'),

('Zabbix','ZBX-012','medium','P3','Memory Usage >85% – app-01',
 'Application server memory pressure detected.',
 'SITE-DC2','app-01','JVM','compute',
 NOW()-INTERVAL '24 days 9 hours', NOW()-INTERVAL '24 days 9 hours',
 'RESOLVED','JVM heap leak – fixed in deploy v2.3.1',1,
 md5('ZBX-012-dc2'),'APAC','Cluster-B','HP','Application',
 'App Ops','APP-OnCall','Silver','ON_TRACK', NOW()-INTERVAL '24 days 9 hours'),

('Zabbix','ZBX-013','low','P4','NTP Drift Detected – app-03',
 'NTP synchronisation offset >500ms.',
 'SITE-DC2','app-03','NTP','compute',
 NOW()-INTERVAL '22 days 11 hours', NOW()-INTERVAL '22 days 11 hours',
 'RESOLVED','NTP server reconfigured',1,
 md5('ZBX-013-dc2'),'APAC','Cluster-B','HP','x86 Compute',
 'Platform Ops','SYS-OnCall','Bronze','ON_TRACK', NOW()-INTERVAL '22 days 11 hours'),

('Zabbix','ZBX-014','high','P2','Interface Down – dist-sw-03 Gi0/1',
 'Uplink interface to core went down unexpectedly.',
 'SITE-DC2','dist-sw-03','Ethernet','network',
 NOW()-INTERVAL '20 days 3 hours', NOW()-INTERVAL '20 days 3 hours',
 'RESOLVED','Fibre optic cable replaced',1,
 md5('ZBX-014-dc2'),'APAC','Cluster-B','Cisco','IP/MPLS',
 'Network Ops','NOC-OnCall','Gold','ON_TRACK', NOW()-INTERVAL '20 days 3 hours'),

('Zabbix','ZBX-015','medium','P3','SNMP Trap: Fan Failure – rack-pdu-02',
 'Cooling fan failure reported in rack PDU.',
 'SITE-DC2','rack-pdu-02','Power','network',
 NOW()-INTERVAL '18 days 16 hours', NOW()-INTERVAL '18 days 16 hours',
 'RESOLVED','Fan unit replaced by facilities',1,
 md5('ZBX-015-dc2'),'APAC','Cluster-B','APC','Power/Cooling',
 'Facilities','FAC-OnCall','Bronze','ON_TRACK', NOW()-INTERVAL '18 days 16 hours'),

('Zabbix','ZBX-016','critical','P1','Database Connection Pool Exhausted',
 'All DB connections in use – new queries queuing.',
 'SITE-DC1','db-primary-01','PostgreSQL','compute',
 NOW()-INTERVAL '15 days 22 hours', NOW()-INTERVAL '15 days 22 hours',
 'RESOLVED','Connection leak in batch job – patched',15,
 md5('ZBX-016-dc1'),'EMEA','Cluster-A','Dell','Database',
 'DBA','DBA-OnCall','Platinum','BREACHED', NOW()-INTERVAL '15 days 22 hours'),

('Zabbix','ZBX-017','high','P2','SSL Certificate Expiring in 7 Days',
 'TLS certificate for api.example.com expires in 7 days.',
 'SITE-DC1','lb-01','HAProxy','network',
 NOW()-INTERVAL '13 days 8 hours', NOW()-INTERVAL '13 days 8 hours',
 'RESOLVED','Certificate renewed via Let''s Encrypt',1,
 md5('ZBX-017-dc1'),'EMEA','Cluster-A','F5','Application',
 'Platform Ops','SYS-OnCall','Gold','ON_TRACK', NOW()-INTERVAL '13 days 8 hours'),

('Zabbix','ZBX-018','medium','P3','Backup Job Failed – db-replica-02',
 'Nightly backup did not complete within SLA window.',
 'SITE-DC1','db-replica-02','PostgreSQL','compute',
 NOW()-INTERVAL '11 days 6 hours', NOW()-INTERVAL '11 days 6 hours',
 'RESOLVED','Storage mount timeout – backup re-ran successfully',1,
 md5('ZBX-018-dc1'),'EMEA','Cluster-A','NetApp','Database',
 'DBA','DBA-OnCall','Silver','ON_TRACK', NOW()-INTERVAL '11 days 6 hours'),

('Zabbix','ZBX-019','low','P5','Ping RTT >200ms – remote-office-01',
 'ICMP round trip time elevated to remote office.',
 'SITE-REMOTE','remote-gw-01','ICMP','network',
 NOW()-INTERVAL '9 days 13 hours', NOW()-INTERVAL '9 days 13 hours',
 'RESOLVED','ISP maintenance window – resolved automatically',1,
 md5('ZBX-019-rem'),'Americas','Cluster-C','Cisco','WAN',
 'Network Ops','NOC-OnCall','Bronze','ON_TRACK', NOW()-INTERVAL '9 days 13 hours'),

-- ── Alertmanager – regular alarms ──────────────────────────────────────────
('Alertmanager','AM-010','high','P2','Node Memory Pressure – k8s-node-07',
 'Memory available <10% on Kubernetes worker node.',
 'SITE-DC1','k8s-node-07','Kubernetes','compute',
 NOW()-INTERVAL '27 days 14 hours', NOW()-INTERVAL '27 days 14 hours',
 'RESOLVED','Workload rescheduled – node drained and rebooted',2,
 md5('AM-010-dc1'),'EMEA','Cluster-A','AWS','Cloud/Kubernetes',
 'Platform Ops','K8S-OnCall','Gold','ON_TRACK', NOW()-INTERVAL '27 days 14 hours'),

('Alertmanager','AM-011','medium','P3','PVC Disk Usage >80% – prometheus-pvc',
 'Prometheus persistent volume above 80% capacity.',
 'SITE-DC1','k8s-node-02','Kubernetes','compute',
 NOW()-INTERVAL '25 days 10 hours', NOW()-INTERVAL '25 days 10 hours',
 'RESOLVED','Retention period reduced from 90d to 30d',1,
 md5('AM-011-dc1'),'EMEA','Cluster-A','AWS','Cloud/Kubernetes',
 'Platform Ops','K8S-OnCall','Bronze','ON_TRACK', NOW()-INTERVAL '25 days 10 hours'),

('Alertmanager','AM-012','high','P2','Redis Cache Hit Rate <50%',
 'Cache effectiveness degraded – elevated DB load.',
 'SITE-DC1','cache-01','Redis','application',
 NOW()-INTERVAL '23 days 9 hours', NOW()-INTERVAL '23 days 9 hours',
 'RESOLVED','Cache invalidation bug fixed in v3.2.0',3,
 md5('AM-012-dc1'),'EMEA','Cluster-A','AWS','Application',
 'App Ops','APP-OnCall','Silver','ON_TRACK', NOW()-INTERVAL '23 days 9 hours'),

('Alertmanager','AM-013','critical','P1','Service Down – auth-service',
 'Authentication service returning 503 to all requests.',
 'SITE-DC1','app-server-05','auth-service','application',
 NOW()-INTERVAL '19 days 1 hour', NOW()-INTERVAL '19 days 1 hour',
 'RESOLVED','Deadlock in session store – service restarted',25,
 md5('AM-013-dc1'),'EMEA','Cluster-A','AWS','Application',
 'App Ops','APP-OnCall','Platinum','BREACHED', NOW()-INTERVAL '19 days 1 hour'),

('Alertmanager','AM-014','medium','P3','High GC Pause – notification-service',
 'JVM garbage collection pauses >500ms detected.',
 'SITE-DC2','app-server-07','notification-service','application',
 NOW()-INTERVAL '16 days 11 hours', NOW()-INTERVAL '16 days 11 hours',
 'RESOLVED','Heap tuned from 2GB to 4GB',2,
 md5('AM-014-dc2'),'APAC','Cluster-B','AWS','Application',
 'App Ops','APP-OnCall','Silver','ON_TRACK', NOW()-INTERVAL '16 days 11 hours'),

('Alertmanager','AM-015','high','P2','Kafka Consumer Lag >100k',
 'bpm-orchestrator consumer group lagging 100k+ messages.',
 'SITE-DC1','kafka-broker-02','Kafka','application',
 NOW()-INTERVAL '12 days 15 hours', NOW()-INTERVAL '12 days 15 hours',
 'RESOLVED','Consumer threads increased from 4 to 16',7,
 md5('AM-015-dc1'),'EMEA','Cluster-A','AWS','Messaging',
 'Platform Ops','K8S-OnCall','Gold','ON_TRACK', NOW()-INTERVAL '12 days 15 hours'),

-- Alertmanager + Zabbix co-occurrence (both fire at 10am 8 days ago)
('Alertmanager','AM-016','high','P2','API Gateway 5xx Rate Spike',
 '5xx error rate jumped to 8% – correlates with upstream alarm.',
 'SITE-DC1','api-gw-01','Kong','application',
 NOW()-INTERVAL '8 days 10 hours', NOW()-INTERVAL '8 days 10 hours',
 'RESOLVED','Upstream service overload – rate limiting applied',18,
 md5('AM-016-dc1'),'EMEA','Cluster-A','AWS','Application',
 'App Ops','APP-OnCall','Gold','AT_RISK', NOW()-INTERVAL '8 days 10 hours'),

('Zabbix','ZBX-020','high','P2','Web Server Thread Pool Saturated',
 'All request handler threads in use – queue forming.',
 'SITE-DC1','web-02','Nginx','compute',
 NOW()-INTERVAL '8 days 10 hours 5 minutes', NOW()-INTERVAL '8 days 10 hours 5 minutes',
 'RESOLVED','Auto-scaled to 3 additional instances',9,
 md5('ZBX-020-dc1'),'EMEA','Cluster-A','AWS','Application',
 'Platform Ops','SYS-OnCall','Gold','AT_RISK', NOW()-INTERVAL '8 days 10 hours 5 minutes'),

-- ── Grafana – application alerts ────────────────────────────────────────────
('Grafana','GF-010','medium','P3','Dashboard Load Time >3s',
 'Grafana dashboard rendering slow – datasource timeout.',
 'SITE-DC1','grafana-01','Grafana','application',
 NOW()-INTERVAL '29 days 15 hours', NOW()-INTERVAL '29 days 15 hours',
 'RESOLVED','Index added to metrics table',1,
 md5('GF-010-dc1'),'EMEA','Cluster-A','AWS','Observability',
 'Platform Ops','SYS-OnCall','Bronze','ON_TRACK', NOW()-INTERVAL '29 days 15 hours'),

('Grafana','GF-011','low','P4','Loki Log Ingestion Rate Drop',
 'Log ingestion rate dropped 40% – possible agent issue.',
 'SITE-DC1','loki-01','Loki','application',
 NOW()-INTERVAL '21 days 12 hours', NOW()-INTERVAL '21 days 12 hours',
 'RESOLVED','Promtail agent restarted on affected nodes',1,
 md5('GF-011-dc1'),'EMEA','Cluster-A','AWS','Observability',
 'Platform Ops','SYS-OnCall','Bronze','ON_TRACK', NOW()-INTERVAL '21 days 12 hours'),

('Grafana','GF-012','high','P2','Synthetic Monitor Failure – checkout flow',
 'End-to-end checkout test failing from 3 probe locations.',
 'SITE-DC1','synthetics','checkout-service','application',
 NOW()-INTERVAL '17 days 8 hours', NOW()-INTERVAL '17 days 8 hours',
 'RESOLVED','Payment API schema change caused failure – fixed',6,
 md5('GF-012-dc1'),'EMEA','Cluster-A','AWS','Application',
 'App Ops','APP-OnCall','Gold','BREACHED', NOW()-INTERVAL '17 days 8 hours'),

('Grafana','GF-013','medium','P3','Trace Error Rate >2% – inventory-service',
 'Distributed traces showing >2% error rate on inventory-service.',
 'SITE-DC2','app-server-09','inventory-service','application',
 NOW()-INTERVAL '14 days 13 hours', NOW()-INTERVAL '14 days 13 hours',
 'RESOLVED','Third-party supplier API intermittent failures',4,
 md5('GF-013-dc2'),'APAC','Cluster-B','AWS','Application',
 'App Ops','APP-OnCall','Silver','ON_TRACK', NOW()-INTERVAL '14 days 13 hours'),

('Grafana','GF-014','low','P5','Metric Cardinality Warning',
 'Label cardinality approaching Prometheus limit (2M series).',
 'SITE-DC1','prometheus-01','Prometheus','application',
 NOW()-INTERVAL '10 days 16 hours', NOW()-INTERVAL '10 days 16 hours',
 'RESOLVED','High-cardinality labels removed from 3 exporters',1,
 md5('GF-014-dc1'),'EMEA','Cluster-A','AWS','Observability',
 'Platform Ops','SYS-OnCall','Bronze','ON_TRACK', NOW()-INTERVAL '10 days 16 hours'),

('Grafana','GF-015','high','P2','SLO Burn Rate Alert – order-service',
 'Error budget burning 14x faster than threshold.',
 'SITE-DC1','app-server-04','order-service','application',
 NOW()-INTERVAL '7 days 9 hours', NOW()-INTERVAL '7 days 9 hours',
 'FIRING','Increased error rate post-deployment v4.1.0',11,
 md5('GF-015-dc1'),'EMEA','Cluster-A','AWS','Application',
 'App Ops','APP-OnCall','Gold','AT_RISK', NOW()-INTERVAL '7 days 9 hours'),

-- ── Dynatrace – mixed, for 4th source in co-occurrence ─────────────────────
('Dynatrace','DT-001','critical','P1','Dynatrace: Service Response Degradation',
 'order-service response time degraded >300% vs baseline.',
 'SITE-DC1','app-server-04','order-service','application',
 NOW()-INTERVAL '5 days 2 hours 9 minutes', NOW()-INTERVAL '5 days 2 hours 9 minutes',
 'FIRING','Correlated with infrastructure outage at 02:00',20,
 md5('DT-001-dc1'),'EMEA','Cluster-A','AWS','Application',
 'App Ops','APP-OnCall','Platinum','BREACHED', NOW()-INTERVAL '5 days 2 hours 9 minutes'),

('Dynatrace','DT-002','high','P2','Dynatrace: Failure Rate Spike',
 'Failure rate on payment-service jumped from 0.1% to 12%.',
 'SITE-DC1','app-server-03','payment-service','application',
 NOW()-INTERVAL '5 days 2 hours 14 minutes', NOW()-INTERVAL '5 days 2 hours 14 minutes',
 'FIRING','Cascaded from auth-service outage',14,
 md5('DT-002-dc1'),'EMEA','Cluster-A','AWS','Application',
 'App Ops','APP-OnCall','Gold','BREACHED', NOW()-INTERVAL '5 days 2 hours 14 minutes'),

('Dynatrace','DT-010','medium','P3','Dynatrace: DB Connection Count Elevated',
 'Active DB connections 3x above normal baseline.',
 'SITE-DC2','db-02','MySQL','compute',
 NOW()-INTERVAL '22 days 14 hours', NOW()-INTERVAL '22 days 14 hours',
 'RESOLVED','Connection pooling misconfiguration after upgrade',5,
 md5('DT-010-dc2'),'APAC','Cluster-B','Dell','Database',
 'DBA','DBA-OnCall','Silver','ON_TRACK', NOW()-INTERVAL '22 days 14 hours'),

('Dynatrace','DT-011','low','P4','Dynatrace: CDN Cache Miss Rate >40%',
 'CDN cache miss rate elevated – origin traffic increased.',
 'SITE-DC1','cdn-edge-01','CDN','application',
 NOW()-INTERVAL '6 days 11 hours', NOW()-INTERVAL '6 days 11 hours',
 'RESOLVED','Cache-Control headers corrected in static assets',1,
 md5('DT-011-dc1'),'EMEA','Cluster-A','Cloudflare','Application',
 'App Ops','APP-OnCall','Bronze','ON_TRACK', NOW()-INTERVAL '6 days 11 hours'),

('Dynatrace','DT-012','high','P2','Dynatrace: Throughput Drop >50%',
 'Requests per second halved vs rolling 1-hour baseline.',
 'SITE-DC1','app-server-02','api-service','application',
 NOW()-INTERVAL '4 days 10 hours', NOW()-INTERVAL '4 days 10 hours',
 'RESOLVED','Load balancer health check misconfigured post-deploy',8,
 md5('DT-012-dc1'),'EMEA','Cluster-A','AWS','Application',
 'App Ops','APP-OnCall','Gold','BREACHED', NOW()-INTERVAL '4 days 10 hours'),

-- ── Recent active alarms (last 3 days, still FIRING) ───────────────────────
('Zabbix','ZBX-030','high','P2','Disk I/O Latency >100ms – storage-01',
 'Block device average latency above SLA threshold.',
 'SITE-DC1','storage-01','iSCSI','compute',
 NOW()-INTERVAL '2 days 8 hours', NOW()-INTERVAL '2 days 8 hours',
 'FIRING','Storage controller firmware issue under investigation',3,
 md5('ZBX-030-dc1'),'EMEA','Cluster-A','NetApp','Storage',
 'Storage Ops','STO-OnCall','Gold','BREACHED', NOW()-INTERVAL '2 days 8 hours'),

('Alertmanager','AM-020','medium','P3','PodRestartRate High – logging-agent',
 'logging-agent DaemonSet pods restarting every 15 minutes.',
 'SITE-DC1','k8s-node-05','logging-agent','compute',
 NOW()-INTERVAL '1 day 14 hours', NOW()-INTERVAL '1 day 14 hours',
 'FIRING','Log volume spike exhausting agent buffer',6,
 md5('AM-020-dc1'),'EMEA','Cluster-A','AWS','Cloud/Kubernetes',
 'Platform Ops','K8S-OnCall','Silver','AT_RISK', NOW()-INTERVAL '1 day 14 hours'),

('Grafana','GF-020','high','P2','SLO Burn Rate Critical – auth-service',
 'Auth service error budget depleted at 28x expected rate.',
 'SITE-DC1','app-server-05','auth-service','application',
 NOW()-INTERVAL '3 hours', NOW()-INTERVAL '3 hours',
 'FIRING','JWT validation timeout under heavy load',9,
 md5('GF-020-dc1'),'EMEA','Cluster-A','AWS','Application',
 'App Ops','APP-OnCall','Platinum','AT_RISK', NOW()-INTERVAL '3 hours'),

('Zabbix','ZBX-031','critical','P1','BGP Route Table Instability',
 'Rapid BGP updates causing route table churn – >500 updates/min.',
 'SITE-DC1','core-router-02','BGP','network',
 NOW()-INTERVAL '1 hour', NOW()-INTERVAL '1 hour',
 'FIRING','Suspected upstream ISP route leak',12,
 md5('ZBX-031-dc1'),'EMEA','Cluster-A','Cisco','IP/MPLS',
 'Network Ops','NOC-OnCall','Platinum','BREACHED', NOW()-INTERVAL '1 hour'),

('Alertmanager','AM-021','critical','P1','Node CPU Throttling – k8s-node-04',
 'CPU throttling at 95% – pods performance severely degraded.',
 'SITE-DC1','k8s-node-04','Kubernetes','compute',
 NOW()-INTERVAL '45 minutes', NOW()-INTERVAL '45 minutes',
 'FIRING','Crypto mining workload bypassed admission control',7,
 md5('AM-021-dc1'),'EMEA','Cluster-A','AWS','Cloud/Kubernetes',
 'Security Ops','SOC-OnCall','Platinum','BREACHED', NOW()-INTERVAL '45 minutes'),

('Dynatrace','DT-020','high','P2','Dynatrace: Anomaly on order-service',
 'Unusual request spike pattern detected by AI baseline.',
 'SITE-DC1','app-server-04','order-service','application',
 NOW()-INTERVAL '30 minutes', NOW()-INTERVAL '30 minutes',
 'FIRING','Correlated with BGP instability upstream',5,
 md5('DT-020-dc1'),'EMEA','Cluster-A','AWS','Application',
 'App Ops','APP-OnCall','Gold','AT_RISK', NOW()-INTERVAL '30 minutes')

ON CONFLICT (dedup_hash) WHERE status IN ('FIRING','OPEN') DO NOTHING;
